
export LD_LIBRARY_PATH := ../../:$(LD_LIBRARY_PATH)

CPP=g++
NVCC=nvcc

ARCH=sm_20

CUDA_HOME=/home/wfchiang/lib/cuda-6.0

export LD_LIBRARY_PATH := $(CUDA_HOME)/lib64:$(LD_LIBRARY_PATH)


NN=32
BB=32
R=2 
# N_VARS = NN * BB * 2
N_VARS=2048
S3FP_DIR=../../../src


all: compile 

compile: fft-32 fft-64

dataio.o: dataio.cpp dataio.h 

fft-32: dataio.o 
	$(NVCC) -DFT=float -DFT2=float2 -Dmake_FT2=make_float2 -DNN=$(NN) -DBB=$(BB) -DR=$(R) -c fft.cu -arch=$(ARCH) 

	$(CPP) fft.o dataio.o -o fft-32 -lcuda -lcudart -L $(CUDA_HOME)/lib64 

fft-64: dataio.o 
	$(NVCC) -DFT=double -DFT2=double2 -Dmake_FT2=make_double2 -DNN=$(NN) -DBB=$(BB) -DR=$(R) -c fft.cu -arch=$(ARCH) 

	$(CPP) fft.o dataio.o -o fft-64 -lcuda -lcudart -L $(CUDA_HOME)/lib64


TIMEOUT=20 
RESOURCE=SVE
RSEED=0

ERR_FUNC = REL 
ERR_OPT = LAST 

REL_DELTA=0.001
CHECK_UNSTABLE_ERROR=false
INPUTLB=-100.0
INPUTUB=100.0

INPUT_FILE = random_input 
EXE_LP = fft-32
EXE_HP = fft-64
OUTPUT_LP = fft-32_output
OUTPUT_HP = fft-64_output


create-base-conf:
	@echo "==== generate s3fp_setting ====" 
	@echo N_VARS = $(N_VARS) > s3fp_setting 
	@echo TIMEOUT = $(TIMEOUT) >> s3fp_setting
	@echo RESOURCE = $(RESOURCE) >> s3fp_setting
	@echo RSEED = $(RSEED) >> s3fp_setting
	@echo ERR_FUNC = $(ERR_FUNC) >> s3fp_setting 
	@echo ERR_OPT = $(ERR_OPT) >> s3fp_setting 
	@echo REL_DELTA = $(REL_DELTA) >> s3fp_setting
	@echo UNIFORM_INPUT = true >> s3fp_setting
	@echo UNIFORM_INPUTLB = $(INPUTLB) >> s3fp_setting
	@echo UNIFORM_INPUTUB = $(INPUTUB) >> s3fp_setting
	@echo N_INPUT_REPEATS = 10 >> s3fp_setting
	@echo INPUT_FILE = $(INPUT_FILE) >> s3fp_setting 
	@echo EXE_LP = $(EXE_LP) >> s3fp_setting 
	@echo EXE_HP = $(EXE_HP) >> s3fp_setting 
	@echo OUTPUT_LP = $(OUTPUT_LP) >> s3fp_setting 
	@echo OUTPUT_HP = $(OUTPUT_HP) >> s3fp_setting 

test-urt: create-base-conf
	@echo RT = URT >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp

test-bgrt: create-base-conf
	@echo RT = BGRT >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp

test-ils: create-base-conf
	@echo RT = ILS >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp

test-pso: create-base-conf
	@echo RT = PSO >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp

clean:
	-rm *~
	-rm *.o 
	-rm fft-32 fft-64 
	-rm __outdump
	-rm best_input_* 
	-rm fft-gpu_input
	-rm fft-gpu_output_*
	-rm $(INPUT_FILE) 
	-rm $(OUTPUT_LP) $(OUTPUT_HP) 
	-rm s3fp_setting 
