
CC=g++

S3FP_DIR=../../..

N=1024
TIMEOUT=5
RESOURCE=TIME # or TIME
INPUTLB=-100.0
INPUTUB=100.0
RSEED=0
ERR_OPT=LAST
ERR_FUNC=ABSREL
REL_DELTA=0.001 

all: imbalanced-32 imbalanced-64 imbalanced-128 

imbalanced-32: imbalanced-reduction.c
	$(CC) -o imbalanced-32 -DFT=float imbalanced-reduction.c
imbalanced-64: imbalanced-reduction.c
	$(CC) -o imbalanced-64 -DFT=double imbalanced-reduction.c
imbalanced-128: imbalanced-reduction.c
	$(CC) -o imbalanced-128 -DFT=__float128 imbalanced-reduction.c 

create-base-conf:
	@echo "==== generate s3fp_setting ====" 
	@echo N_VARS = $(N) > s3fp_setting 
	@echo INPUT_FILE = random_input >> s3fp_setting 
	@echo EXE_LP = ./imbalanced-32 >> s3fp_setting 
	@echo OUTPUT_LP = test_output_32 >> s3fp_setting 
	@echo EXE_HP = ./imbalanced-128 >> s3fp_setting 
	@echo OUTPUT_HP = test_output_128 >> s3fp_setting 
	@echo TIMEOUT = $(TIMEOUT) >> s3fp_setting
	@echo RESOURCE = $(RESOURCE) >> s3fp_setting
	@echo RSEED = $(RSEED) >> s3fp_setting
	@echo ERR_OPT = $(ERR_OPT) >> s3fp_setting 
	@echo ERR_FUNC = $(ERR_FUNC) >> s3fp_setting 
	@echo REL_DELTA = $(REL_DELTA) >> s3fp_setting
	@echo UNIFORM_INPUT = true >> s3fp_setting
	@echo UNIFORM_INPUTLB = $(INPUTLB) >> s3fp_setting
	@echo UNIFORM_INPUTUB = $(INPUTUB) >> s3fp_setting

test-urt: create-base-conf
	@echo RT = URT >> s3fp_setting
	@echo "==== run s3fp ====" 
	@$(S3FP_DIR)/s3fp 

test-bgrt: create-base-conf
	@echo RT = BGRT >> s3fp_setting
	@echo "==== run s3fp ====" 
	@$(S3FP_DIR)/s3fp 

test-ils: create-base-conf
	@echo RT = ILS >> s3fp_setting
	@echo "==== run s3fp ====" 
	@$(S3FP_DIR)/s3fp 

test-pso: create-base-conf
	@echo RT = PSO >> s3fp_setting
	@echo "==== run s3fp ====" 
	@$(S3FP_DIR)/s3fp 

clean:
	-rm imbalanced-32 imbalanced-64 imbalanced-128 
	-rm test_input* test_output_*
	-rm __outdump
	-rm best_input